name: palmerodev_porfolio
description: "My portfolio :)"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_bloc: ^9.1.1
  equatable: ^2.0.7
  go_router: ^16.3.0
  bloc: ^9.1.0
  get_it: ^8.2.0
  json_annotation: ^4.9.0
  freezed_annotation: ^3.1.0
  envied: ^1.3.1
  intl: ^0.20.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  json_serializable: ^6.11.1
  build_runner: ^2.10.1
  flutter_gen_runner: ^5.12.0
  freezed: ^3.2.3
  envied_generator: ^1.3.1
  freezed_lint: ^0.0.12

flutter:
  uses-material-design: true
  generate: true
